import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — DataBard",
  description:
    "The terms governing your use of DataBard, an AI analyst that connects to your data catalog and delivers weekly audio briefings.",
};

const LAST_UPDATED = "2025-01-15";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--bg)] text-[var(--text)] px-4 py-12 relative enter-up">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <Link href="/" className="text-[var(--text-muted)] text-sm no-underline">
            ← Back to DataBard
          </Link>
          <h1 className="text-[28px] font-extrabold mt-4 mb-2">Terms of Service</h1>
          <p className="text-[var(--text-muted)] text-sm">
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        <div className="flex flex-col gap-8 text-sm leading-relaxed">
          <section>
            <p className="text-[var(--text-muted)]">
              These terms govern your use of DataBard, available at{" "}
              <a
                href="https://databard.persidian.com"
                className="text-[var(--accent)] no-underline"
              >
                databard.persidian.com
              </a>
              . By creating an account or using the service, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Service description</h2>
            <p className="text-[var(--text-muted)]">
              DataBard is an AI analyst that connects to your data catalog, computes health scores
              and lineage risk, and delivers weekly audio briefings alongside a dashboard. The
              service supports catalogs including OpenMetadata, dbt, Coral, Dune, and The Graph.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Acceptable use</h2>
            <ul className="flex flex-col gap-2 list-disc pl-5 text-[var(--text-muted)]">
              <li>Do not abuse the API — respect rate limits and fair-use boundaries.</li>
              <li>Do not share your account credentials or API tokens with others.</li>
              <li>Do not use DataBard for any illegal or unauthorized purpose.</li>
              <li>Do not attempt to reverse-engineer, scrape, or disrupt the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Account responsibility</h2>
            <p className="text-[var(--text-muted)]">
              You are responsible for the API tokens you connect to DataBard and for all activity
              performed under your account. You may revoke a connected source&apos;s access at any
              time by removing the credential or rotating the token at the source. Keep your
              account secure and notify us promptly of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Data source permissions</h2>
            <p className="text-[var(--text-muted)]">
              You must have authorization to connect the data sources you provide to DataBard. You
              are responsible for ensuring that fetching metadata from those sources complies with
              your organization&apos;s policies and any applicable agreements. DataBard is not
              liable for unauthorized connections.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">AI-generated content</h2>
            <p className="text-[var(--text-muted)]">
              Briefings and analyses are generated by AI from your catalog metadata. They may
              contain inaccuracies or miss context that a human analyst would catch.{" "}
              <span className="text-[var(--text)]">
                Verify critical findings before acting on them.
              </span>{" "}
              DataBard outputs are informational, not professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Limitation of liability</h2>
            <p className="text-[var(--text-muted)]">
              The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
              warranties of any kind. We are not liable for decisions made based on AI-generated
              briefings, for data loss, or for any indirect or consequential damages arising from
              your use of DataBard. Your use of the service is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Billing</h2>
            <ul className="flex flex-col gap-2 list-disc pl-5 text-[var(--text-muted)]">
              <li>
                Pro is <span className="text-[var(--text)]">$49/month per team</span>, covering up
                to 5 schemas with unlimited listeners.
              </li>
              <li>You may cancel your subscription at any time.</li>
              <li>
                Fees are billed in advance and are non-refundable for partial months. Access
                continues until the end of the current billing period.
              </li>
              <li>Payment is processed by Stripe; we do not store your card details.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">On-chain attestation</h2>
            <p className="text-[var(--text-muted)]">
              If you use the Solana attestation feature, you are responsible for any transaction
              fees incurred. On-chain attestation data is{" "}
              <span className="text-[var(--text)]">public and permanent</span> — once written, it
              cannot be deleted. Do not include sensitive information in attested reports.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Changes to these terms</h2>
            <p className="text-[var(--text-muted)]">
              We may update these terms from time to time. We will notify you by email before any
              material changes take effect. Continued use of DataBard after changes take effect
              constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3">Contact</h2>
            <p className="text-[var(--text-muted)]">
              Questions about these terms? Reach us at{" "}
              <a
                href="mailto:legal@databard.persidian.com"
                className="text-[var(--accent)] no-underline"
              >
                legal@databard.persidian.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-[var(--border)]">
          <Link href="/" className="text-[var(--text-muted)] text-sm no-underline">
            ← Back to DataBard
          </Link>
        </div>
      </div>
    </main>
  );
}
